### ISSUE TITLE
执行 build_behavior.py,  build_audience.py 后，npz 文件没有保存下来

### ISSUE THREAD

**Issue by gitzyong812** [JiDong-CS/icme2019-bytedance-grand-challenge#1]
感谢作者分享。我按照说明执行 build_behavior.py,  build_audience.py 后，本应该生成 npz 文件，但是并没有文件保存下来，想请教下怎么回事儿

**Comment by JiDong-CS** [comment]
抱歉，没有及时回复。是正常执行完成，没有报错信息吗？另外，是否所有文件都在用一目录下，包括data目录？

**Comment by gitzyong812** [comment]
已经解决了，不过有点久，只记得是升级了一个包，然后就好了，应该是升级了 scipy

**Comment by greenary-John** [comment]
> 已经解决了，不过有点久，只记得是升级了一个包，然后就好了，应该是升级了 scipy

不，是名字写错了，build_behavior里的3个name需要改成target_name
