### ISSUE TITLE
大佬，可以分享一份数据吗？

### ISSUE THREAD

**Issue by weiyinwei** [JiDong-CS/icme2019-bytedance-grand-challenge#3]
之前把数据放服务器上了，结果服务器坏了，所有数据都没了，官方的数据也不能用了。大佬如果方便是否可以给一个分享链接，track2的就可以，非常感谢非常感谢。

**Comment by Joyzhangaoyang** [comment]
同求数据集

**Comment by JiDong-CS** [comment]
链接: https://pan.baidu.com/s/1ECS8WzRAfqDT8LHpesGV9g 提取码: wgwq

**Comment by weiyinwei** [comment]
太感谢了。不知道您是否还有特征数据呢，audio数据可以分享下吗？

**Comment by Outstandingwinner** [comment]
大佬，数据集可以再分享一下吗？链接失效了 谢谢！
