### ISSUE TITLE
您好，能否分享通道2的数据集

### ISSUE THREAD

**Issue by houxiaona** [JiDong-CS/icme2019-bytedance-grand-challenge#5]

**Comment by A-three** [comment]
> _没有提供描述。_
请问您找到了吗

**Comment by JiDong-CS** [comment]
> > _没有提供描述。_
> > 请问您找到了吗

链接: https://pan.baidu.com/s/1LMmmiK0iRt4xKJgLB3BcVA 提取码: rwh3
链接: https://pan.baidu.com/s/1Q2oq9vg8ytXxq65VSkCNjg 提取码: mkdw

**Comment by houxiaona** [comment]
感谢您提供的帮助，不胜感激


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"JiDong"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月21日(星期四) 下午3:17
收件人:&nbsp;"JiDong-CS/icme2019-bytedance-grand-challenge"<icme2019-bytedance-grand-challenge@noreply.github.com&gt;;
抄送:&nbsp;"951215305"<951215305@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [JiDong-CS/icme2019-bytedance-grand-challenge] 您好，能否分享通道2的数据集 (#5)





   
没有提供描述。
 请问您找到了吗
   
链接: https://pan.baidu.com/s/1LMmmiK0iRt4xKJgLB3BcVA 提取码: rwh3
 链接: https://pan.baidu.com/s/1Q2oq9vg8ytXxq65VSkCNjg 提取码: mkdw

**Comment by zkailinzhang** [comment]
百度链接失效了,可以再发个链接吗?
