### ISSUE TITLE
你好，请问数据集可以发一份吗

### ISSUE THREAD

**Issue by maohx** [JiDong-CS/icme2019-bytedance-grand-challenge#6]

**Comment by zkailinzhang** [comment]
求数据 +1

**Comment by JiDong-CS** [comment]
链接: https://pan.baidu.com/s/1RdQt5jPlEqFIwcW91SLc2w 提取码: gwrf 
链接: https://pan.baidu.com/s/1zW9V43Lm4PumRa39cATvnQ 提取码: tgwm

**Comment by maohx** [comment]
谢谢你，你端午节快乐！





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: kailin zhang <notifications@github.com&gt;
发送时间: 2020年6月23日 20:16
收件人: JiDong-CS/icme2019-bytedance-grand-challenge <icme2019-bytedance-grand-challenge@noreply.github.com&gt;
抄送: Huixia Mao <842183987@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[JiDong-CS/icme2019-bytedance-grand-challenge] 你好，请问数据集可以发一份吗 (#6)





 
求数据 +1

**Comment by JamesTensor** [comment]
百度链接已经过期，可以再发送一遍吗？谢谢

**Comment by hibayesian** [comment]
@maohx 能再分享一下数据集吗？
